[package]
name = "rustybrain"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
   "rustybrain-gtk",
   "rustybrain-core",
]

[dependencies]
color-eyre = "0.5.11"

rustybrain-gtk = { path = "rustybrain-gtk" }
rustybrain-core = { path = "rustybrain-core" }
anyhow = "1.0.58"
