[package]
edition = "2021"
name = "rustybrain-core"
version = "0.1.0"
[dependencies]
chrono = "0.4.19"
serde = { version = "1.0", features = ["derive"] }
tantivy = "0.18.0"
toml = "0.5"
tree-sitter = "0.20.8"
tree-sitter-markdown = "0.7.1"
