[package]
name = "rustybrain-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.19.5"
tree-sitter-markdown = "0.7.1"
